package apierror

import (
	"net/http"
)

func GoogleOneTapTokenInvalid() Error {
	return New(http.StatusBadRequest, &mainError{
		shortMessage: "Google One Tap token is invalid",
		longMessage:  "The provided Google One Tap token is invalid. Make sure you're using a valid token generated by Google.",
		code:         GoogleOneTapTokenInvalidCode,
	})
}
