package apierror

import "net/http"

func TicketExpired() Error {
	return New(http.StatusBadRequest, &mainError{
		shortMessage: "ticket has expired",
		longMessage:  "This ticket has expired and cannot be used anymore.",
		code:         TicketExpiredCode,
	})
}

func TicketInvalid() Error {
	return New(http.StatusBadRequest, &mainError{
		shortMessage: "ticket is invalid",
		longMessage:  "This ticket is invalid. Make sure you're using a valid ticket generated by Clerk.",
		code:         TicketInvalidCode,
	})
}
